services:
  ollama:
    build: 
      context: .docker/ollama
      dockerfile: Dockerfile
    environment:
      MODELS: ${OLLAMA_MODELS}
      OLLAMA_MAX_LOADED_MODELS: ${OLLAMA_MAX_LOADED_MODELS}
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s

  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/data

volumes:
  minio-data: {}
  pg-data: {}
  ollama-data: {}
  chroma-data: {}
  clickhouse-data: {}
  clickhouse-logs: {}
  redis-data: {}